/* ─────────────────────────────────────────────────────────────────────────
   RAPID FIRE QUIZ BANK  —  All courses, all sections
   Each card: { label, q, a }
     label — short "CX · Topic" tag shown in the card header
     q     — question text
     a     — answer text
───────────────────────────────────────────────────────────────────────── */
window.RAPID_FIRE_BANK = (function () {

  function section(label, cards) {
    return cards.map(function (c) { return { label: label, q: c.q, a: c.a }; });
  }

  var c1 = [].concat(
    section('C1 · Hardware', [
      { q: 'What is the difference between RAM and storage? Why does a program need RAM to run?',
        a: 'RAM is volatile and extremely fast — the CPU reads/writes it directly while a program runs. Storage is non-volatile and slower — programs live there permanently but must be loaded into RAM to execute.' },
      { q: 'A user\'s computer is very slow and has 8 GB RAM with 16 GB of programs open. What is likely happening?',
        a: 'The OS is using virtual memory (page file/swap) on disk because RAM is exhausted. Disk is far slower than RAM, causing heavy slowdowns — commonly called "thrashing."' },
      { q: 'How many bits are in 3 bytes? What is binary 1001 in decimal?',
        a: '3 bytes = 24 bits. Binary 1001 = 8+0+0+1 = 9.' },
      { q: 'A technician opens a desktop without an anti-static wrist strap. What risk does this create?',
        a: 'ESD (Electrostatic Discharge) — static built up in the body can discharge into sensitive components, silently damaging or destroying the CPU, RAM, GPU, or motherboard.' },
      { q: 'What is the purpose of POST and what might beep codes indicate?',
        a: 'POST (Power-On Self Test) verifies critical hardware (CPU, RAM, GPU, storage) before the OS loads. Beep codes signal which component failed — pattern varies by BIOS/UEFI vendor.' },
      { q: 'Which storage interface is fastest: SATA SSD, M.2 NVMe, or HDD?',
        a: 'M.2 NVMe is fastest (3,000–7,000 MB/s), then SATA SSD (~550 MB/s), then HDD (80–160 MB/s).' },
    ]),
    section('C1 · OS & Software', [
      { q: 'What is a kernel, and how do applications interact with it?',
        a: 'The kernel is the privileged core of the OS that directly manages hardware. Applications communicate with it through system calls — requests to read a file, send network data, etc.' },
      { q: 'A printer was just connected to a Windows PC but isn\'t working. What type of software is most likely missing?',
        a: 'A device driver — software that translates OS-level commands into hardware-specific instructions the printer understands.' },
      { q: 'What is the difference between a Type 1 and Type 2 hypervisor? Give an example of each.',
        a: 'Type 1 runs directly on bare-metal hardware (e.g., VMware ESXi, Hyper-V) — higher performance. Type 2 runs on top of an existing OS (e.g., VirtualBox, VMware Workstation) — easier to set up.' },
      { q: 'What does GPL require of derivative software, and how does this differ from the MIT license?',
        a: 'GPL requires any derivative code to also be released under GPL (copyleft). MIT is permissive — you can incorporate MIT-licensed code into proprietary products without releasing your source.' },
      { q: 'What do the three parts of semantic versioning represent? (e.g., 2.1.3)',
        a: 'MAJOR = breaking change; MINOR = new feature (backwards-compatible); PATCH = bug fix.' },
      { q: 'What is the difference between open source and freeware?',
        a: 'Open source: source code is publicly available and can be inspected, modified, and distributed. Freeware: free to use at no cost, but source code is not available.' },
    ]),
    section('C1 · Networking Basics', [
      { q: 'What is the functional difference between a hub and a switch?',
        a: 'A hub broadcasts every frame to all ports (one collision domain, no intelligence). A switch learns MAC addresses and forwards frames only to the correct port (separate collision domain per port).' },
      { q: 'A home user has one device from their ISP that handles both internet and local Wi-Fi. What is it called?',
        a: 'A modem/router combo (gateway or residential gateway). The modem converts the ISP signal; the router manages the LAN and provides Wi-Fi via a built-in WAP.' },
      { q: 'Which cable category supports 10 Gbps over 100 metres?',
        a: 'Cat 6a. (Cat 6 only supports 10G up to 55 m; Cat 6a extends to the full 100 m.)' },
      { q: 'Why is a star topology preferred over a bus topology in modern LANs?',
        a: 'In a star topology, only the device with the failed link goes down. In a bus topology, a single break in the shared cable takes the entire segment offline.' },
      { q: 'A device has IP 192.168.1.50. Is this public or private?',
        a: 'Private — 192.168.0.0/16 is a RFC 1918 private range, not routable on the public internet.' },
      { q: 'What does a router do that a switch cannot?',
        a: 'A router operates at Layer 3 and forwards traffic between different networks using IP addresses. A switch operates at Layer 2 and can only move traffic within a single network using MAC addresses.' },
    ]),
    section('C1 · Troubleshooting', [
      { q: 'A user says "my email doesn\'t work." What are your first three questions?',
        a: '1) "When did it stop / what changed?" 2) "Can you access the internet or other apps?" 3) "Is anyone else having the same problem?" — determines if it\'s user-specific or infrastructure-wide.' },
      { q: 'You apply a fix but the problem returns the next day. Which troubleshooting step did you likely skip?',
        a: 'You found a symptom, not the root cause (step 2 was incomplete). Reopen the ticket, revisit step 2 with new info, find the underlying cause, and implement a real fix.' },
      { q: 'A machine is randomly shutting off. Would you approach this top-down or bottom-up? Why?',
        a: 'Bottom-up — random shutdowns are often hardware/environmental (overheating, PSU, RAM failure). Start at the physical layer before jumping to software.' },
      { q: 'At what tier would a password reset typically be handled?',
        a: 'Tier 1 (Help Desk) — password resets are a standard scripted procedure.' },
      { q: 'You need to open a desktop to reseat RAM. What should you do first?',
        a: 'Power off the machine, unplug it from the wall, and attach an anti-static wrist strap grounded to the case before touching any components.' },
      { q: 'What are the 7 steps of the troubleshooting methodology?',
        a: '1) Identify the problem, 2) Establish a theory, 3) Test the theory, 4) Plan the action, 5) Implement, 6) Verify the fix, 7) Document.' },
    ]),
    section('C1 · Customer Service', [
      { q: 'A user says "nothing ever works around here." How do you respond?',
        a: 'Acknowledge the frustration first: "I hear you, and I\'m sorry this has been frustrating. Let me focus on getting this fixed right now." Stay calm — avoid being defensive.' },
      { q: 'What is the difference between an incident and a problem in ITIL terms?',
        a: 'Incident = unplanned disruption requiring fast restoration (e.g., restart a crashed service). Problem = root cause investigation of why incidents occur — takes longer but prevents recurrence.' },
      { q: 'A recurring P2 ticket appears every Monday for the same server. What ITIL process should be initiated?',
        a: 'Problem management — open a Problem record to investigate the root cause rather than just patching it each week.' },
      { q: 'Why is it important to update a ticket with your findings even if you haven\'t resolved it yet?',
        a: 'It creates a shared audit trail so others don\'t repeat work, timestamps your progress for SLA compliance, and provides data for post-incident review.' },
      { q: 'What is a runbook and when would you use one?',
        a: 'A runbook is a documented step-by-step procedure for a routine task (e.g., restart the mail server). Used to ensure consistent execution and allow less experienced staff to handle critical tasks safely.' },
      { q: 'A Tier 1 tech is 30 minutes from breaching a P1 SLA. What should they do?',
        a: 'Escalate immediately — notify supervisor or on-call Tier 2/3 engineer. Never let a P1 SLA breach silently; proactive communication lets management reassign resources before the breach.' },
    ])
  );

  var c2 = [].concat(
    section('C2 · OSI & TCP/IP', [
      { q: 'At which OSI layer does a switch operate?',
        a: 'Layer 2 — Data Link. Switches use MAC addresses to forward frames.' },
      { q: 'What is the PDU at the Network layer called?',
        a: 'Packet.' },
      { q: 'Which TCP/IP layer combines OSI layers 5, 6, and 7?',
        a: 'The Application layer.' },
      { q: 'What does the Transport layer add to data during encapsulation?',
        a: 'A TCP or UDP header (creating a segment or datagram), adding source/destination port numbers and sequencing info.' },
      { q: 'Which OSI layer handles encryption and data formatting (e.g., JPEG, TLS)?',
        a: 'Layer 6 — Presentation.' },
      { q: 'Name two differences between the OSI model and the TCP/IP model.',
        a: 'OSI has 7 layers; TCP/IP has 4. OSI is conceptual/academic; TCP/IP is the working model on the real internet. OSI separates Session/Presentation/Application; TCP/IP merges them.' },
    ]),
    section('C2 · Subnetting', [
      { q: 'What is the subnet mask for a /26 prefix?',
        a: '255.255.255.192' },
      { q: 'How many usable hosts does a /28 network provide?',
        a: '14  (2⁴ – 2 = 14)' },
      { q: 'What is the network address for host 10.0.1.100 on a /27 network?',
        a: '/27 block size = 32. 100 ÷ 32 = 3 remainder 4 → block starts at 96. Network address: 10.0.1.96' },
      { q: 'A host shows address 169.254.1.50. What does this indicate?',
        a: 'DHCP failed or no DHCP server was reachable. The host auto-assigned an APIPA address (169.254.0.0/16).' },
      { q: 'You need exactly 30 usable hosts per subnet. What prefix length do you use?',
        a: '/27  (2⁵ – 2 = 30 usable hosts)' },
      { q: 'What is the broadcast address of 192.168.10.64/26?',
        a: 'Block starts at .64, size = 64 addresses. Broadcast = 192.168.10.127' },
    ]),
    section('C2 · Data Link', [
      { q: 'What protocol maps an IP address to a MAC address on the local network?',
        a: 'ARP (Address Resolution Protocol).' },
      { q: 'How many bytes is a MAC address, and how is it written?',
        a: '6 bytes (48 bits), written as 6 pairs of hex digits separated by colons or dashes (e.g., AA:BB:CC:DD:EE:FF).' },
      { q: 'What is the broadcast MAC address?',
        a: 'FF:FF:FF:FF:FF:FF' },
      { q: 'What is the maximum payload size of an Ethernet frame and what is it called?',
        a: '1500 bytes — this is the MTU (Maximum Transmission Unit) for standard Ethernet.' },
      { q: 'What does the OUI in a MAC address tell you?',
        a: 'The first 3 bytes (OUI = Organizationally Unique Identifier) identify the device manufacturer (e.g., Intel, Cisco).' },
      { q: 'How does a switch differ from a hub in terms of collision domains?',
        a: 'Each port on a switch is its own collision domain. A hub has one shared collision domain for all ports.' },
    ]),
    section('C2 · Transport & Ports', [
      { q: 'Walk through the TCP three-way handshake in order.',
        a: 'Client sends SYN → Server replies SYN-ACK → Client sends ACK. Connection is now established.' },
      { q: 'What port does HTTPS use, and what does it add over HTTP?',
        a: 'Port 443. HTTPS = HTTP over TLS, adding encryption, server authentication via certificates, and data integrity.' },
      { q: 'Which protocol would you use for live video streaming, and why?',
        a: 'UDP — faster (no handshake or retransmission overhead) and a dropped frame is less noticeable than jitter from waiting for retransmits.' },
      { q: 'What port does RDP use?',
        a: '3389' },
      { q: 'A firewall blocks all traffic to port 22. What functionality is lost?',
        a: 'SSH access — secure remote shell, SCP file transfers, and SFTP would all be blocked.' },
      { q: 'What are the three port number ranges and their boundaries?',
        a: 'Well-known: 0–1023 | Registered: 1024–49151 | Dynamic/ephemeral: 49152–65535' },
    ]),
    section('C2 · App Layer Services', [
      { q: 'What DNS record type maps a hostname to an IPv4 address?',
        a: 'A record.' },
      { q: 'Spell out and explain each step of the DHCP DORA process.',
        a: 'Discover (client broadcasts for DHCP server) → Offer (server offers an IP lease) → Request (client formally requests the offer) → Acknowledge (server confirms the lease).' },
      { q: 'An HTTP response returns 403. What does this mean, and how is it different from 401?',
        a: '403 = Forbidden (authenticated but not permitted). 401 = Unauthorized (authentication required but not provided or failed).' },
      { q: 'What type of NAT does a typical home router use? How does it share one IP among many devices?',
        a: 'PAT (Port Address Translation) / NAT overload. Maps each private IP:port pair to the public IP with a unique port, tracking sessions in the NAT table.' },
      { q: 'You can access a site by IP but not by domain name. What is the likely problem?',
        a: 'DNS resolution is failing. The IP-based request bypasses DNS. Run nslookup or dig on the domain to verify.' },
      { q: 'What is DNS TTL and why does it matter for troubleshooting?',
        a: 'TTL is how long a DNS record is cached before re-querying. A high TTL means stale entries linger after a change — important when troubleshooting after a DNS migration.' },
    ]),
    section('C2 · Network Troubleshooting', [
      { q: 'What command shows the ARP cache on Windows? On Linux?',
        a: 'Windows: arp -a  |  Linux: arp -n  (or ip neigh)' },
      { q: 'You can ping 8.8.8.8 but can\'t load google.com in a browser. What is most likely wrong?',
        a: 'DNS resolution is failing. The device can reach the internet but can\'t translate domain names to IPs. Run nslookup google.com or dig google.com.' },
      { q: 'What does ipconfig /flushdns do and when would you use it?',
        a: 'Clears the local DNS resolver cache. Useful when DNS records have changed (e.g., server migration) but the old cached entry is still being returned.' },
      { q: 'What is the difference between a site-to-site VPN and a remote access VPN?',
        a: 'Site-to-site connects two full networks permanently (e.g., two offices), handled by router/firewall appliances. Remote access VPN connects a single user\'s device to a network on-demand.' },
      { q: 'Why might a stateful firewall be preferable to a stateless one for allowing web traffic?',
        a: 'A stateful firewall tracks connection state and automatically allows return traffic for established sessions. A stateless firewall needs explicit rules for return traffic, creating potential security gaps.' },
      { q: 'What are the non-overlapping 2.4 GHz channels (US) and why does it matter?',
        a: 'Channels 1, 6, and 11. Using the same or adjacent channels as a neighbour causes co-channel or adjacent-channel interference, reducing throughput.' },
    ])
  );

  var c3 = [].concat(
    section('C3 · Navigation', [
      { q: 'What character separates directories in a Windows path? What about Linux?',
        a: 'Windows uses backslash (\\); Linux uses forward slash (/).' },
      { q: 'Which flag shows hidden (dot) files with ls on Linux?',
        a: 'ls -a  — in Linux, any file starting with a dot is hidden.' },
      { q: 'What is the difference between a file\'s "size" and its "size on disk"?',
        a: 'Size = actual data in the file. Size on disk = physical space used, always a multiple of the cluster size — so it can be larger than the actual file data.' },
      { q: 'Which PowerShell flag forces ls to show hidden files?',
        a: 'ls -Force <directory>' },
      { q: 'What Linux command opens a command\'s manual page?',
        a: 'man <command>' },
      { q: 'What is the difference between an absolute path and a relative path?',
        a: 'Absolute paths start from the root (e.g. /home/user or C:\\Users\\). Relative paths start from the current working directory (e.g. ../Desktop).' },
    ]),
    section('C3 · Users & Perms', [
      { q: 'What Linux command lets a standard user run a single command with root privileges?',
        a: 'sudo' },
      { q: 'What does chmod 644 mean? Who can do what?',
        a: 'Owner: rw- (read + write). Group: r-- (read only). Others: r-- (read only). (6 = 4+2, 4 = read only)' },
      { q: 'Which file in Linux lists all user accounts on the system?',
        a: '/etc/passwd' },
      { q: 'What is the difference between an ACL and a DACL?',
        a: 'ACL (Access Control List) is the general concept of permission lists. DACL (Discretionary ACL) is the Windows implementation — "discretionary" because the owner controls access.' },
      { q: 'Which PowerShell command lists all local groups on a Windows machine?',
        a: 'Get-LocalGroup' },
      { q: 'What numeric value represents read + write + execute in Linux permissions?',
        a: '7  (r=4 + w=2 + x=1 = 7)' },
    ]),
    section('C3 · Packages', [
      { q: 'What is the difference between apt and dpkg on Linux?',
        a: 'apt is high-level: fetches packages from repos and resolves dependencies. dpkg is low-level: installs/removes .deb files directly but won\'t auto-resolve dependencies.' },
      { q: 'What package format does the Microsoft Store use to distribute UWP apps?',
        a: 'Appx packages.' },
      { q: 'What is the first thing Windows does when a new device is plugged in?',
        a: 'Windows queries the hardware ID to find the right driver.' },
      { q: 'What command shows the current Linux kernel version?',
        a: 'uname -r' },
      { q: 'Which Linux command upgrades the entire system including the kernel?',
        a: 'sudo apt full-upgrade' },
      { q: 'What is a DLL and why is it useful?',
        a: 'A DLL (Dynamic Link Library) is a shared code library multiple programs can use simultaneously — avoids duplicating code across apps, all share one loaded copy in memory.' },
    ]),
    section('C3 · Filesystems', [
      { q: 'Which filesystem is readable and writable on Windows, Mac, and Linux?',
        a: 'FAT32 (and exFAT for files over 4 GB).' },
      { q: 'What are the key differences between MBR and GPT partition tables?',
        a: 'MBR: max 2 TB disk, max 4 primary partitions, older BIOS. GPT: 2 TB+, virtually unlimited partitions, required by UEFI (modern firmware).' },
      { q: 'What is the difference between a symbolic (soft) link and a hard link?',
        a: 'Symbolic link: points to a file\'s path — breaks if the target moves/is deleted. Hard link: points directly to the inode — survives even if the original filename is deleted.' },
      { q: 'Why must you properly unmount a drive before removing it?',
        a: 'The OS uses a data buffer (RAM) to stage writes. Proper unmounting flushes the buffer to disk. Removing early can corrupt the filesystem.' },
      { q: 'What is the Linux equivalent of Windows\' Master File Table (MFT)?',
        a: 'Inodes, stored in an inode table.' },
      { q: 'Which Linux command shows free disk space across the whole machine in human-readable format?',
        a: 'df -h' },
      { q: 'What is /etc/fstab and why should it use UUIDs instead of device names?',
        a: '/etc/fstab defines filesystems to mount automatically at boot. UUIDs are used because device names like /dev/sdb can change between reboots — UUIDs always identify the same partition.' },
    ]),
    section('C3 · Processes', [
      { q: 'What is PID 1 in Linux and what does it do?',
        a: 'The init process (PID 1) — the first process created by the kernel at boot. It\'s the parent of all other processes and starts system services.' },
      { q: 'What is the difference between SIGTERM and SIGKILL?',
        a: 'SIGTERM asks the process to terminate gracefully (it can clean up). SIGKILL instantly force-kills it with no cleanup — cannot be caught or ignored. Last resort only.' },
      { q: 'Which Linux command shows a live view of top resource-consuming processes?',
        a: 'top  (or htop for an improved interactive version)' },
      { q: 'What does the STAT code "S" mean in ps output?',
        a: 'S = interruptible sleep — the process is waiting for something (I/O, user input) and can be interrupted.' },
      { q: 'What signal does Ctrl+C send to a process?',
        a: 'SIGINT (signal interrupt) — a polite request to stop the current process.' },
      { q: 'Where does Linux store security and authorization logs?',
        a: '/var/log/auth.log' },
      { q: 'What is Unix Epoch time?',
        a: 'The number of seconds elapsed since midnight January 1, 1970 UTC. Used as a universal timestamp in Unix/Linux system logs.' },
      { q: 'Which command follows a log file live as new entries are written?',
        a: 'tail -f <logfile>' },
    ]),
    section('C3 · OS in Practice', [
      { q: 'What is the difference between SSH and RDP?',
        a: 'SSH gives you a remote command line (text-only, lightweight). RDP gives you a full graphical desktop — you can see and control the remote machine\'s GUI.' },
      { q: 'What Windows CLI tool creates RDP connections?',
        a: 'mstsc.exe (Microsoft Terminal Services Client)' },
      { q: 'What is PuTTY and why is it useful on Windows?',
        a: 'PuTTY is a free open-source SSH/Telnet client for Windows. It lets you securely connect to Linux/Unix machines from Windows, and supports SCP via pscp.exe.' },
      { q: 'What does the Linux dd command do? How would you clone disk sda to sdb?',
        a: 'dd is a low-level byte-for-byte copy tool. To clone: dd if=/dev/sda of=/dev/sdb  (if = input file, of = output file)' },
      { q: 'What is the main advantage of network-initiated (PXE) OS deployment?',
        a: 'Scales much better — hundreds of machines can receive their OS image simultaneously from a central server, with no physical media or staff at each machine.' },
      { q: 'Which Windows tool browses system event logs from the GUI?',
        a: 'Event Viewer (eventvwr.msc)' },
      { q: 'What is Safe Mode and when would you use it?',
        a: 'Safe Mode boots Windows with only minimum required drivers and services. Use it when Windows won\'t boot normally, or to isolate driver/software conflicts.' },
    ])
  );

  var c4 = [].concat(
    section('C4 · Sys Admin', [
      { q: 'What are the three common server form factors?',
        a: 'Tower (standalone, desktop-like), Rack (slim, slides into a rack), Blade (ultra-thin modules sharing a chassis for power and networking).' },
      { q: 'What is a KVM switch and why is it important to a sys admin?',
        a: 'A KVM (Keyboard-Video-Mouse) switch lets one keyboard, monitor, and mouse control many servers — critical when the network is down and remote access is unavailable.' },
      { q: 'Name the four stages of the hardware lifecycle in order.',
        a: 'Procurement → Deployment → Maintenance → Retirement.' },
      { q: 'What is the difference between a production environment and a test environment?',
        a: 'Production is the live environment end users depend on. A test environment mirrors production but is isolated — changes are validated there before going live. Never test in production.' },
      { q: 'Which Linux command records a terminal session to a log file?',
        a: 'script session.log — captures the session in ANSI format until you type exit.' },
      { q: 'What is a rollback plan and when should you prepare it?',
        a: 'Documented steps to undo a change. It must be prepared before making any change — not after something goes wrong.' },
      { q: 'What does IT Change Management standardize?',
        a: 'A formal process for planning, communicating, and implementing technical changes. Each change is documented with responsible party, scope, date/time, rollback plan, and risk level.' },
      { q: 'What three things does a reproduction case document?',
        a: '(1) The steps taken that led to the issue, (2) the unexpected result observed, (3) the expected result.' },
    ]),
    section('C4 · Network Services', [
      { q: 'What is a daemon?',
        a: 'A background process that runs continuously, usually starting at boot. It has config files to control its behavior. On Linux, config files live in /etc.' },
      { q: 'What is the key difference between FTP and SFTP?',
        a: 'FTP transmits data in plain text with no encryption. SFTP tunnels FTP over SSH, encrypting the entire connection.' },
      { q: 'Why would you use TFTP instead of SFTP?',
        a: 'TFTP is used for PXE booting — its simplicity (no auth, no encryption) lets it deliver OS images over the network before any OS is loaded on the client.' },
      { q: 'What does NTP do and what is its 128 ms correction limit?',
        a: 'NTP synchronizes system clocks across a network. It auto-corrects only if the clock is within 128 ms of true time, adjusting gradually. If further off, you must manually set the time first.' },
      { q: 'What four services does Dnsmasq provide in a single package?',
        a: 'DNS, DHCP, TFTP, and PXE services.' },
      { q: 'You can ping an IP address but cannot reach a domain by name. What type of problem is this?',
        a: 'A DNS problem, not a network problem. Use nslookup <domain> to diagnose.' },
      { q: 'What is the difference between a dedicated server and a virtualized instance?',
        a: 'Dedicated: one service per physical machine — better performance, higher cost, underutilizes resources. Virtualized: multiple services share one machine via a hypervisor — efficient, flexible, supports live migration.' },
      { q: 'What Linux command lists all services and shows which are active or inactive?',
        a: 'sudo service --status-all  — [+] = active, [-] = inactive, [?] = unknown.' },
    ]),
    section('C4 · Software Services', [
      { q: 'What is the only email protocol used for sending mail?',
        a: 'SMTP (Simple Mail Transfer Protocol).' },
      { q: 'What is the difference between POP3 and IMAP?',
        a: 'POP3 downloads email and removes it from the server — single-device model. IMAP keeps a copy on the server so your inbox syncs across multiple devices.' },
      { q: 'What do SPF, DKIM, and DMARC each do?',
        a: 'SPF — lists authorized sending IPs for a domain. DKIM — cryptographically signs outgoing messages. DMARC — ties SPF and DKIM together and tells receivers what to do with failing mail.' },
      { q: 'What is the relationship between SSL and TLS?',
        a: 'SSL is the deprecated predecessor to TLS. TLS v1.0 was effectively SSL v3.0 renamed. Never use SSL on new systems.' },
      { q: 'What do you need to enable HTTPS on a web server?',
        a: 'A TLS certificate issued by a trusted Certificate Authority (CA). The CA vouches that the certificate legitimately belongs to your domain.' },
      { q: 'When would you choose Samba over NFS for file sharing?',
        a: 'In Windows-heavy or mixed environments — Samba (SMB) integrates natively with Windows and Active Directory. NFS is fast on Linux but slow on Windows.' },
      { q: 'What is the difference between PCL and PostScript printer languages?',
        a: 'PCL (HP) is device-dependent — output can vary across printers. PostScript (Adobe) is device-independent — output is identical on any PS-compatible printer.' },
      { q: 'A user gets a 403 error on your web app. Client-side or server-side? What does it mean?',
        a: 'Client-side (4xx range). 403 Forbidden means the server understood the request but is refusing it — typically a permissions problem.' },
      { q: 'What does autoscaling do and when is it most useful?',
        a: 'Automatically adds or removes compute instances based on actual demand. Most useful for variable-traffic workloads — seasonal spikes, flash sales — so you only pay for capacity when needed.' },
    ]),
    section('C4 · Directory Services', [
      { q: 'What is LDAP and what is it used for?',
        a: 'Lightweight Directory Access Protocol — a simplified protocol for accessing directory services. Used to read and write user, group, and device data in directories like Active Directory and OpenLDAP.' },
      { q: 'What does AAA stand for in centralized management?',
        a: 'Authentication (prove identity), Authorization (determine what\'s allowed), Accounting (log what was done).' },
      { q: 'What does the LDAP Bind operation do?',
        a: 'It authenticates the client to the directory server, establishing the identity the client will act under for all subsequent operations.' },
      { q: 'What is LSDOU and why does the processing order matter?',
        a: 'The GPO application order: Local → Site → Domain → OU. Later settings override earlier ones on conflicts, so the most specific (OU-linked) GPO wins.' },
      { q: 'What clock-skew limit causes Kerberos authentication to fail, and how do you fix it?',
        a: 'More than 5 minutes of difference between client and domain controller. Fix with w32tm /resync.' },
      { q: 'What is the difference between a GPO Policy and a GPO Preference?',
        a: 'Policies are enforced settings re-applied every few minutes — users cannot override them. Preferences are template defaults — users can change them.' },
      { q: 'What is the difference between a Security Group and a Distribution Group in Active Directory?',
        a: 'Security Groups can be granted resource permissions. Distribution Groups are email-only and cannot be used for access control.' },
      { q: 'What are the three AD group scopes?',
        a: 'Domain Local (permissions to a specific resource), Global (group accounts by role within a domain), Universal (group roles across an entire forest).' },
      { q: 'What is an LDIF file and how is it used?',
        a: 'A plain-text file that describes a directory entry or change. Write the LDIF, then pass it to ldapadd, ldapmodify, or ldapdelete.' },
    ]),
    section('C4 · Backups & Recovery', [
      { q: 'What is the difference between RPO and RTO?',
        a: 'RPO (Recovery Point Objective) = max acceptable data loss measured in time. RTO (Recovery Time Objective) = max acceptable downtime — how fast systems must be restored.' },
      { q: 'What does the 3-2-1 backup rule say?',
        a: 'Keep 3 copies of data, on 2 different media types, with 1 copy stored off-site.' },
      { q: 'What is the key difference between a differential and an incremental backup?',
        a: 'Differential: copies everything changed since the last full backup. Incremental: copies only what changed since the last backup of any type — most efficient, but restore requires full + every incremental in order.' },
      { q: 'Why is RAID not a backup solution?',
        a: 'RAID provides storage redundancy but doesn\'t protect against accidental deletion, ransomware, or a site-wide disaster. All copies live together and can be destroyed together.' },
      { q: 'What is the standard medium for long-term archival storage and why?',
        a: 'Magnetic tape — inexpensive and long-lasting compared to hard drives, making it cost-effective for large volumes of rarely-accessed archive data.' },
      { q: 'Describe the three types of disaster recovery sites.',
        a: 'Hot site: fully operational duplicate, minutes to fail over. Warm site: hardware ready, data must be restored, hours to bring online. Cold site: space and power only, days to weeks to provision.' },
      { q: 'What are the five main sections of a post-mortem report?',
        a: '1) Brief summary, 2) Detailed timeline, 3) Root cause, 4) Resolution & recovery, 5) Action items to prevent recurrence.' },
      { q: 'What does rsync do on Linux?',
        a: 'A file-transfer utility that efficiently copies and syncs files, transferring only data that has changed since the last sync.' },
    ])
  );

  return [].concat(c1, c2, c3, c4);
})();
